use master
GO
DROP DATABASE DA_COVID
GO
CREATE DATABASE DA_COVID
GO
USE DA_COVID
GO

CREATE TABLE DON_VI
(
    MaDonVi     INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    TenDonVi    NVARCHAR(30)       NOT NULL,
    MucDoLayLan INT      DEFAULT 0,
    TaiKhoan    VARCHAR(20)        NOT NULL,
    MatKhau     VARCHAR(20)        NOT NULL,
    CreatedAt   DATETIME DEFAULT GETDATE(),
    UpdatedAt   DATETIME DEFAULT GETDATE()
)

CREATE TABLE CO_SO_CACH_LY
(
    MaCSCL  INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    TenCSCL NVARCHAR(60)       NOT NULL,
);

CREATE TABLE DOI_TUONG_NHIEM_BENH
(
    MaNB  INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    TenNB varchar(2)         NOT NULL
)

-- chỉ dành cho F0, F1, F2
/*CREATE TABLE NGUOI_TIEP_XUC
(
    CMND      VARCHAR(12)  NOT NULL PRIMARY KEY,
    HoTen     NVARCHAR(50) NOT NULL,
    GioiTinh  BIT          NOT NULL,
    QuocTich  NVARCHAR(25) NOT NULL,
    SDT       VARCHAR(15)  NOT NULL,
    DaKhaiBao BIT DEFAULT 0
)
*/
CREATE TABLE VACCINE
(
    MaVaccine  INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    TenVaccine NVARCHAR(50)       NOT NULL,
    XuatXu     NVARCHAR(50)       NOT NULL,
)

CREATE TABLE TRIEU_CHUNG
(
    MaTrieuChung  INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    MoTa          NVARCHAR(1000),
    TenTrieuChung NVARCHAR(50)       NOT NULL,
    DaXoa         BIT DEFAULT 0
)

CREATE TABLE PHIEU_KHAI_BAO
(
    MaPhieu   INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    MaNB      INT FOREIGN KEY REFERENCES DOI_TUONG_NHIEM_BENH (MaNB),
    AmTinh    BIT      DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
)

CREATE TABLE CT_TRIEU_CHUNG
(
    MaPhieu      INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu),
    MaTrieuChung INT FOREIGN KEY REFERENCES TRIEU_CHUNG (MaTrieuChung),
    PRIMARY KEY (MaPhieu, MaTrieuChung)
)

CREATE TABLE CT_TIEM_VACCINE
(
    MaPhieu   INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu),
    MaVaccine INT FOREIGN KEY REFERENCES VACCINE (MaVaccine),
    LuotTiem  INT DEFAULT 1,
    NgayTiem  DATE NOT NULL,
    PRIMARY KEY (MaPhieu, LuotTiem)
)

CREATE TABLE NGUOI_KHAI_BAO
(
    MaPhieu   INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu) PRIMARY KEY,
    CMND      VARCHAR(12)  NOT NULL,
    HoTen     NVARCHAR(50) NOT NULL,
    GioiTinh  BIT          NOT NULL,
    QuocTich  NVARCHAR(25) NOT NULL,
    NgaySinh  DATE         NOT NULL,
    SDT       VARCHAR(15)  NOT NULL,
    Email     VARCHAR(20)  NOT NULL,
    SoNha     NVARCHAR(20) NOT NULL,
    TenPhuong NVARCHAR(20) NOT NULL,
    TenQuan   NVARCHAR(20) NOT NULL,
    TenTinh   NVARCHAR(20) NOT NULL
)

-- chỉ dành cho F0, F1, F2
CREATE TABLE CT_TIEP_XUC
(
    MaPhieu    INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu),
    CMNDNTX    VARCHAR(12),
    DiaDiemTX  NVARCHAR(50),
    ThoiGianTX DATE,
    PRIMARY KEY (MaPhieu, CMNDNTX)
--     PRIMARY KEY (MaPhieu)
)

CREATE TABLE PHIEU_TOAN_DAN
(
    MaPhieu INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu) PRIMARY KEY,
    MaDonVi INT FOREIGN KEY REFERENCES DON_VI (MaDonVi),
    DaXoa   BIT DEFAULT 0
)

CREATE TABLE PHIEU_NHAP_CANH
(
    MaPhieu             INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu) PRIMARY KEY,
    MaCSCL              INT FOREIGN KEY REFERENCES CO_SO_CACH_LY (MaCSCL),
    DoiTuong            NVARCHAR(50)  NOT NULL,
    PhuongTien          NVARCHAR(50)  NOT NULL,
    NgayKhoiHanh        DATETIME      NOT NULL,
    NgayNhapCanh        DATETIME      NOT NULL,
    DiaDiemQGKhoiHanh   NVARCHAR(100) NOT NULL,
    DiaDiemTinhKhoiHanh NVARCHAR(100) NOT NULL,
    DiaDiemQGNoiDen     NVARCHAR(100) NOT NULL,
    DiaDiemTinhNoiDen   NVARCHAR(100) NOT NULL,
    DaXoa               BIT DEFAULT 0
)

CREATE TABLE PHIEU_DI_CHUYEN_NOI_DIA
(
    MaPhieu      INT FOREIGN KEY REFERENCES PHIEU_KHAI_BAO (MaPhieu) PRIMARY KEY,
    DiaDiemDi    NVARCHAR(100) NOT NULL,
    DiaDiemDen   NVARCHAR(100) NOT NULL,
    NgayKhoiHanh DATETIME      NOT NULL,
    DaXoa        BIT DEFAULT 0
);
